#!/usr/bin/env bash
# One-command testnet setup for axial_swap (beginner-friendly).
# Run from WSL:  cd soroban && ./scripts/testnet-demo-setup.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# --- Your team keys (public addresses — safe to commit) ---
DEPLOYER_KEY="admin-key"
FUNDER_KEY="treasury-key"
MSME_KEY="my-key"
ADMIN_G="GD67NPG7TKJDE5HEHSPWS3YAWYNHWTLWRSQMTO4NQOVSZAEFPICO3HYG"
FUNDER_G="GBRLGRWUJXJSHJDZQ4OH2SDH7ROF7EWAHI4ZIQM2E6TMONH7IG4P7QKL"
MSME_G="GBCVJCRULTHI74CXNP4QFGE6OSK5XFUYIPPEONRNXS3JQSKA26TDAR66"
NETWORK="testnet"
ASSET_CODE="USDC"
ADVANCE_BPS=8500
MINT_AMOUNT=1000000000

echo "==> Axial testnet demo setup"
echo "    deployer: $DEPLOYER_KEY ($ADMIN_G)"
echo "    funder:   $FUNDER_KEY ($FUNDER_G)"
echo "    msme:     $MSME_KEY ($MSME_G)"

if ! command -v stellar >/dev/null; then
  echo "ERROR: Install Stellar CLI in WSL first."
  exit 1
fi

if ! stellar network ls 2>/dev/null | grep -qx "$NETWORK"; then
  echo "==> Adding testnet network"
  stellar network add testnet \
    --rpc-url https://soroban-testnet.stellar.org:443 \
    --network-passphrase "Test SDF Network ; September 2015"
fi

echo "==> Funding accounts (friendbot)"
for k in "$DEPLOYER_KEY" "$FUNDER_KEY" "$MSME_KEY"; do
  stellar keys fund "$k" --network "$NETWORK" || true
done

echo "==> Building contracts"
make build

WASM="$ROOT/target/wasm32v1-none/release/axial_swap.wasm"
if [[ ! -f "$WASM" ]]; then
  echo "ERROR: Missing $WASM — run make build"
  exit 1
fi

echo "==> Deploying axial_swap"
SWAP_ID=$(stellar contract deploy \
  --wasm "$WASM" \
  --source-account "$DEPLOYER_KEY" \
  --network "$NETWORK" 2>&1 | tee /tmp/axial-deploy.log | tail -1)
# CLI may print only the contract ID on last line; fallback grep
if [[ ! "$SWAP_ID" =~ ^C[A-Z0-9]{55}$ ]]; then
  SWAP_ID=$(grep -oE 'C[A-Z0-9]{55}' /tmp/axial-deploy.log | tail -1)
fi
echo "    axial_swap: $SWAP_ID"

ASSET_LINE="${ASSET_CODE}:${ADMIN_G}"
echo "==> Test USDC asset (issuer = admin)"
TOKEN_ID=$(stellar contract id asset --asset "$ASSET_LINE" --network "$NETWORK")
echo "    token id: $TOKEN_ID"
if ! stellar contract asset deploy \
  --asset "$ASSET_LINE" \
  --source-account "$DEPLOYER_KEY" \
  --network "$NETWORK" 2>&1 | tee /tmp/axial-token.log; then
  if grep -q 'contract already exists' /tmp/axial-token.log; then
    echo "    (already deployed on testnet — reusing)"
  else
    echo "ERROR: asset deploy failed — see /tmp/axial-token.log"
    exit 1
  fi
fi

echo "==> Trustlines (required before mint/transfer)"
for k in "$FUNDER_KEY" "$MSME_KEY"; do
  echo "    $k trusts ${ASSET_CODE}:${ADMIN_G}"
  stellar tx new change-trust \
    --source-account "$k" \
    --line "${ASSET_CODE}:${ADMIN_G}" \
    --network "$NETWORK"
done

echo "==> Minting $MINT_AMOUNT stroops to treasury (funder)"
stellar contract invoke \
  --id "$TOKEN_ID" \
  --source-account "$DEPLOYER_KEY" \
  --network "$NETWORK" \
  -- \
  mint \
  --to "$FUNDER_G" \
  --amount "$MINT_AMOUNT"

echo "==> Initializing axial_swap"
stellar contract invoke \
  --id "$SWAP_ID" \
  --source-account "$DEPLOYER_KEY" \
  --network "$NETWORK" \
  -- \
  initialize \
  --admin "$ADMIN_G" \
  --usdc "$TOKEN_ID" \
  --advance_bps "$ADVANCE_BPS"

mkdir -p deployments
cat > deployments/testnet.json <<EOF
{
  "network": "testnet",
  "passphrase": "Test SDF Network ; September 2015",
  "rpc": "https://soroban-testnet.stellar.org",
  "deployed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "roles": {
    "admin_key": "$DEPLOYER_KEY",
    "admin_public": "$ADMIN_G",
    "funder_key": "$FUNDER_KEY",
    "funder_public": "$FUNDER_G",
    "msme_key": "$MSME_KEY",
    "msme_public": "$MSME_G"
  },
  "contracts": {
    "axial_swap": "$SWAP_ID",
    "usdc_token": "$TOKEN_ID",
    "receivable_token": null,
    "payroll_split": null
  }
}
EOF

cat > .env <<EOF
STELLAR_SOURCE=$DEPLOYER_KEY
STELLAR_NETWORK=$NETWORK
AXIAL_SWAP_CONTRACT_ID=$SWAP_ID
SOROBAN_USDC_TOKEN_ID=$TOKEN_ID
RECEIVABLE_TOKEN_CONTRACT_ID=
PAYROLL_SPLIT_CONTRACT_ID=
USDC_ISSUER_MAINNET=GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN
EOF

WEB_ENV="../web/.env.local"
if FUNDER_SECRET=$(stellar keys secret "$FUNDER_KEY" 2>/dev/null); then
  cat > "$WEB_ENV" <<EOF
# Auto-generated by soroban/scripts/testnet-demo-setup.sh — do not commit
SOROBAN_RPC_URL=https://soroban-testnet.stellar.org
STELLAR_NETWORK_PASSPHRASE=Test SDF Network ; September 2015
AXIAL_SWAP_CONTRACT_ID=$SWAP_ID
SOROBAN_USDC_TOKEN_ID=$TOKEN_ID
STELLAR_FUNDER_SECRET=$FUNDER_SECRET
STELLAR_FUNDER_PUBLIC=$FUNDER_G
STELLAR_MSME_PUBLIC=$MSME_G
EOF
  echo "==> Wrote $WEB_ENV (includes funder secret — gitignored)"
else
  echo "WARN: could not read secret for $FUNDER_KEY — run: ./scripts/write-web-env.sh"
fi

INVOICE_ID="INV-DEMO-$(date +%s)"
echo "==> Test swap: $INVOICE_ID"
if ! stellar contract invoke \
  --id "$SWAP_ID" \
  --source-account "$FUNDER_KEY" \
  --network "$NETWORK" \
  -- \
  execute_advance \
  --funder "$FUNDER_G" \
  --msme "$MSME_G" \
  --invoice_id "$INVOICE_ID" \
  --face_amount 100000; then
  echo "WARN: test swap failed (contract may still be usable — check explorer)"
fi

echo ""
echo "=============================================="
echo "  Testnet setup complete"
echo "=============================================="
echo "  Swap contract:  $SWAP_ID"
echo "  USDC token:     $TOKEN_ID"
echo "  Saved:          deployments/testnet.json"
echo "  Saved:          soroban/.env"
echo ""
echo "  Next — web UI:"
echo "    cd ../web && npm run dev"
echo "    Open http://localhost:3000/liquidity"
echo "    Use a NEW invoice id (not $INVOICE_ID) for another UI swap"
echo "=============================================="
