import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#45464d",
        "primary-container": "#0f172a",
        "inverse-on-surface": "#2b3137",
        background: "#0e141a",
        "on-tertiary": "#3e2d11",
        "inverse-surface": "#dde3eb",
        secondary: "#bcc7de",
        "surface-tint": "#bec6e0",
        surface: "#0e141a",
        "on-error": "#690005",
        "tertiary-container": "#231500",
        "on-tertiary-fixed-variant": "#574425",
        "tertiary-fixed": "#fcdeb5",
        "on-primary-fixed": "#131b2e",
        error: "#ffb4ab",
        "on-tertiary-fixed": "#271901",
        "primary-fixed-dim": "#bec6e0",
        "on-surface": "#dde3eb",
        "on-primary": "#283044",
        "surface-dim": "#0e141a",
        "surface-container-low": "#161c22",
        "secondary-fixed": "#d8e3fb",
        "surface-container": "#1a2026",
        tertiary: "#dec29a",
        "inverse-primary": "#565e74",
        "on-primary-container": "#798098",
        "on-background": "#dde3eb",
        "on-error-container": "#ffdad6",
        outline: "#909097",
        "surface-container-high": "#242b31",
        "surface-bright": "#333a40",
        "secondary-fixed-dim": "#bcc7de",
        "on-tertiary-container": "#957d5a",
        "on-secondary-fixed": "#111c2d",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-variant": "#2f353c",
        "secondary-container": "#3e495d",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed-dim": "#dec29a",
        "surface-container-highest": "#2f353c",
        "surface-container-lowest": "#080f14",
        primary: "#bec6e0",
        "on-secondary": "#263143",
        "on-secondary-container": "#aeb9d0",
        "error-container": "#93000a",
        "on-surface-variant": "#c6c6cd",
        "primary-fixed": "#dae2fd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "margin-tablet": "32px",
        gutter: "32px",
        unit: "8px",
        "container-max": "1440px",
      },
      fontFamily: {
        "label-md": ["var(--font-geist-sans)", "sans-serif"],
        "body-md": ["var(--font-geist-sans)", "sans-serif"],
        "headline-xl": ["var(--font-geist-sans)", "sans-serif"],
        "headline-lg": ["var(--font-geist-sans)", "sans-serif"],
        "body-lg": ["var(--font-geist-sans)", "sans-serif"],
        "headline-md": ["var(--font-geist-sans)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-geist-sans)", "sans-serif"],
        "label-sm": ["var(--font-geist-sans)", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
